server:
  port: 8083 # Puerto para el Payment Service

spring:
  application:
    name: payment-service

  # 1. CONFIGURACIÓN DE BASE DE DATOS H2 (EN MEMORIA)
  datasource:
    url: jdbc:h2:mem:paymentdb
    driverClassName: org.h2.Driver
    username: sa
    password: admin

  jpa:
    show-sql: true
    hibernate:
      # create-drop es esencial para asegurar que la tabla Payment se cree al inicio,
      # especialmente después de fallos o al usar H2 en memoria.
      ddl-auto: create-drop
    properties:
      hibernate:
        # Esto es opcional, ya que Spring lo detecta, pero no causa problema dejarlo.
        dialect: org.hibernate.dialect.H2Dialect

  # 2. CONFIGURACIÓN DE RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin